### PR TITLE
NodeJS NPM Package

### PR DESCRIPTION
**Pull request by klarkc**

### CODE REVIEW

**Comment by DataTables** [comment]
Thank you for this. Getting my npm etc packages sorted out os high on my to do list - I'll be looking at this in detail as soon as possible.

**Comment by reintroducing** [comment]
I'd love for this to get merged as we pull all our items from npm on our site and i've had to add this manually every time its updated.  Is there any way you can prioritize this at some point soon? I greatly appreciate you working on this plugin and I don't want to seem needy but I think a lot of people would appreciate this update.

**Comment by DataTables** [comment]
DataTables and all of its extensions are now available on NPM and Bower as [described in this blog post](http://datatables.net/blog/2015-11-09). They contain compiled files (CSS rather than SCSS like in this repo for example).

I haven't updated the various bugs about NPM (etc) yet as I need to do another release - for example the Responsive 2.0.0 packages actually miss the Bootstrap integration JS file (the air turned blue when I realised). I expect to do a 2.0.1 release next week.

I'll probably publish this repo as source files still (since most of the other extensions have their source files published), but the `datatables.net*` repos are the best way to consume DataTables via NPM now.

**Comment by reintroducing** [comment]
Just saw the blog post from another issue I was running into. Thank you very much.

**Comment by DataTables** [comment]
I should have closed this with my last post - sorry for not. I'm still debating whether or not to publish the source repos on npm, but the distribution repos are there for now.

**Pull request closed without merging**
