### PR TITLE
Modify _columnVisibility to use "pri-xxx" to set column priority

### PR DESCRIPTION
**Pull request by loueradun**
Adding the class "pri-xxx" to a column will set the priority of that column.  All columns marked as "all" will still be shown first, then instead of displaying the remaining columns based on left to right sort order, it will show them based on their priority.  For example, a column with a class of "pri-1" will display before a column with a class of "pri-2", even if the column with class "pri-2" comes before the other column.

### CODE REVIEW

**Comment by loueradun** [comment]
My coworker requested this feature here: https://datatables.net/forums/discussion/22700/responsive-shows-hidden-columns-again/p2

Can we please get this integrated into the core javascript as it is impossible to modify the internal methods outside of the core js file.  This makes maintenance very difficult.

**Comment by DataTables** [comment]
Hi,

Thanks for the PR! Looks good on a quick scan. I'm working on other things at the moment so I can't review it properly just now, but I will try to do so as soon as I can. I'd quite like the ability to set priority using the initialisation options and would probably prefer using a `data-priority` attribute rather than class name, which I can look at doing when merging in.

Can you confirm that you are happy for this to be merged in under the MIT license if I do pull it in?

**Comment by loueradun** [comment]
Thanks for the quick feedback.  I was considering adding a priority attribute to the responsive settings as well, however the proposed solution minimized the number of changes to the core code which makes maintenance a bit easier for updates.  However either way will work fine for our purposes.

One thing I did not take into account in my changes is that changes to the CSS, followed by a call to recalc will not recalculate the priority.  This can be easily fixed by removing the columns.sorted check, however we don't currently anticipate making priority changes on the fly so I added that logic to assist in performance when recalculating the tables.  That may be moot if the priority gets added to the responsive settings anyways.

Feel free to use the PR however you'd like under the MIT license.  Thank you for your great work on the datatables projects.

**Comment by DataTables** [comment]
Sorry its taken so long to get this in! I've added this ability to Responsive now. It uses a `columns.responsivePriority` option in the DataTables initialisation or a `data-priority` attribute in the header cell (rather than a class name) to set the priority.

Many thanks for highlighting this issue and the initial PR - hugely helpful!

**Pull request closed without merging**
